### ISSUE TITLE
Retrait de code et matériel protégé

### ISSUE THREAD

**Issue by beaueric** [charlesfranciscodev/inf3105#1]
Bonjour,
Pourriez-vous retirer de votre dépôt inf3105 le code et les documents suivants :
examens, exercices, laboratoires et quiz ?

Merci,

**Comment by charlesfranciscodev** [comment]
Bonjour, je vais demander aux 3 personnes qui ont créer un fork de retirer leur dépôt de GitHub. Ensuite, je vais effacer le dépôt original (celui-ci) de GitHub.

**Comment by charlesfranciscodev** [comment]
2 forks ont été effacés. Il en reste encore un fork a effacer. J'attends la réponse de la troisième personne.

**Comment by charlesfranciscodev** [comment]
Je n'ai pas réussi à contacter Melissa Farradji, qui est la troisième personne avec un fork. Pouvez-vous lui demander d'effacer son fork?

**Comment by beaueric** [comment]
Merci du suivi. Je vais tenter de joindre cette personne.
Cette personne doit-elle retirer son fork pour que vous puissiez retirer votre dépôt ?

**Comment by charlesfranciscodev** [comment]
Non, mais si j'efface mon dépôt avant elle, son dépôt devient le dépôt "parent".
À ce moment là, vous pourrez créer un autre "issue" sur son dépôt car il ne sera plus considéré comme un fork.
Donc, svp confirmez avec moi, ensuite je vais effacer ce dépôt.

**Comment by beaueric** [comment]
Et si vous renommez le dépôt pour enlever 3105 du nom, cela permet-il d'éviter que l'autre dépôt ne devienne parent ?
Sans fermer le dépôt, il serait auss bon de supprimer un certains nombre de fichiers et d'en faire un commit. Les fichiers restent certes dans l'historique, mais je crois qu'ils ne seront plus considérés dans les résultats de recherche. Ce qui m'embête le plus, c'est que le tout soit trop facilement trouvable.
Merci !

**Comment by charlesfranciscodev** [comment]
Je vais effacer ce dépôt. Il reste encore un fork sur GitHub, donc ce dépôt deviendra le parent.
